import { Investor, Transaction } from "../models/index.js";
import { calculateFinancials } from "../utils/financialCalc.js";

// MOCK current NAV map for demonstration. In a real app, fetch this from a live API.
const MOCK_CURRENT_NAV = {
  "Axis Bluechip Fund": 45.2,
  "SBI Small Cap Fund": 120.5,
};

export const getAllInvestors = async (req, res) => {
  try {
    const investors = await Investor.find().populate("transactions");
    console.log("Fetched investors:", investors);

    const summary = investors.map((inv) => {
      console.log(
        `Calculating metrics for investor: ${inv.transactions[0]?.currentNav}`,
      );
      // Aggregate all transactions across all schemes for total portfolio metrics
      const metrics = calculateFinancials(
        inv.transactions,
        inv.transactions[0]?.currentNav,
      );
      return {
        id: inv._id,
        name: inv.name,
        panNumber: inv.panNumber,
        folioCount: new Set(inv.transactions.map((t) => t.folioNumber)).size,
        totalInvestment: metrics.investedAmount,
        currentValue: metrics.currentValue,
        absoluteReturn: metrics.absoluteReturn,
        xirr: metrics.calculatedXirr,
      };
    });

    res.json(summary);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const portfolioSummary = async (req, res) => {
  try {
    const { investorId } = req.params;
    const investor =
      await Investor.findById(investorId).populate("transactions");
    res.json(investor);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const createInvestorsBulk = async (req, res) => {
  try {
    const payload = req.body; // The JSON array above

    for (const investorData of payload) {
      // 1. Save all transactions for this investor
      const savedTransactions = await Transaction.insertMany(
        investorData.transactions,
      );

      // 2. Extract the ObjectIds generated by MongoDB
      const transactionIds = savedTransactions.map((t) => t._id);

      // 3. Create and save the Investor with the linked ObjectIds
      await Investor.create({
        name: investorData.name,
        panNumber: investorData.panNumber,
        transactions: transactionIds,
      });
    }

    res.status(201).json({ message: "Data successfully synced." });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};
