import { Investor, Transaction } from "../models/index.js";
import { calculateFinancials } from "../utils/financialCalc.js";

export const getAllInvestors = async (req, res) => {
  try {
    const investors = await Investor.find().populate("transactions");

    const summary = investors.map((inv) => {
      // Aggregate all transactions across all schemes for total portfolio metrics
      const metrics = calculateFinancials(inv.transactions);
      return {
        id: inv._id,
        name: inv.name,
        panNumber: inv.panNumber,
        folioCount: metrics.schemeDetails.length,
        totalInvestment: metrics.portfolioSummary.totalInvestedAmount,
        currentValue: metrics.portfolioSummary.totalCurrentValue,
        absoluteReturn: metrics.portfolioSummary.totalAbsoluteReturn,
        xirr: metrics.portfolioSummary.totalXirr,
      };
    });

    res.json(summary);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const portfolioSummary = async (req, res) => {
  try {
    const { investorId } = req.params;
    let investor = await Investor.findById(investorId).populate("transactions");

    let metrics = calculateFinancials(investor.transactions);

    let investorData = {
      name: investor.name,
      panNumber: investor.panNumber,
      transactions: investor.transactions,
      transactionMetrics: {
        folioCount: metrics.schemeDetails.length,
        schemeCount: metrics.schemeDetails.length,
        totalInvestment: metrics.portfolioSummary.totalInvestedAmount,
        currentMarketValue: metrics.portfolioSummary.totalCurrentValue,
        totalGainLoss: metrics.portfolioSummary.totalGainLoss,
        absoluteReturn: metrics.portfolioSummary.totalAbsoluteReturn,
        xirr: metrics.portfolioSummary.totalXirr,
      },
    };

    res.json(investorData);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

export const getSchemeWiseSummary = async (req, res) => {
  try {
    const { investorId } = req.params;
    let investor = await Investor.findById(investorId).populate("transactions");

    let metrics = calculateFinancials(investor.transactions);

    let schemeWiseData = metrics.schemeDetails.map((scheme) => ({
      schemeName: scheme.scheme,
      folioNumber: scheme.folio,
      unitsHeld: scheme.unitsHeld,
      avgPurchaseNav: scheme.avgPurchaseNav,
      currentNav: scheme.currentNav,
      investedAmount: scheme.investedAmount,
      currentValue: scheme.currentValue,
      gainLoss: scheme.gainLoss,
      returnPercent: scheme.absoluteReturn,
      xirr: scheme.calculatedXirr,
    }));

    res.json(schemeWiseData);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// export const createInvestorsBulk = async (req, res) => {
//   try {
//     const payload = req.body; // The JSON array above

//     for (const investorData of payload) {
//       // 1. Save all transactions for this investor
//       const savedTransactions = await Transaction.insertMany(
//         investorData.transactions,
//       );

//       // 2. Extract the ObjectIds generated by MongoDB
//       const transactionIds = savedTransactions.map((t) => t._id);

//       // 3. Create and save the Investor with the linked ObjectIds
//       await Investor.create({
//         name: investorData.name,
//         panNumber: investorData.panNumber,
//         transactions: transactionIds,
//       });
//     }

//     res.status(201).json({ message: "Data successfully synced." });
//   } catch (error) {
//     res.status(500).json({ error: error.message });
//   }
// };

export const createInvestorsBulk = async (req, res) => {
  try {
    // 1. Extract the JSON from the uploaded file buffer (Multer)
    if (!req.file) {
      return res.status(400).json({ error: "No file uploaded from frontend." });
    }

    const jsonString = req.file.buffer.toString("utf-8");
    const payload = JSON.parse(jsonString);

    // 2. Loop through the parsed payload
    for (const investorData of payload) {
      // Check if investor already exists to prevent duplicate PAN crashes
      const existingInvestor = await Investor.findOne({
        panNumber: investorData.panNumber,
      });

      if (existingInvestor) {
        continue; // Skip this iteration and move to the next investor
      }

      // 3. Save all transactions for this investor
      const savedTransactions = await Transaction.insertMany(
        investorData.transactions,
      );

      // 4. Extract the ObjectIds generated by MongoDB
      const transactionIds = savedTransactions.map((t) => t._id);

      // 5. Create and save the Investor with the linked ObjectIds
      await Investor.create({
        name: investorData.name,
        panNumber: investorData.panNumber,
        transactions: transactionIds,
      });
    }

    res.status(201).json({
      message: "Data successfully synced and relationships established.",
    });
  } catch (error) {
    console.error("Bulk Upload Error:", error);
    res
      .status(500)
      .json({ error: error.message || "Failed to process bulk upload." });
  }
};
